# Generated by Django 3.2.8 on 2021-11-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_alter_garden_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='date',
        ),
    ]
