# Generated by Django 3.2.8 on 2021-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_remove_garden_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
