# Generated by Django 3.2.8 on 2021-11-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_garden_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('characteristics', models.CharField(max_length=500)),
                ('recommendations', models.CharField(max_length=500)),
            ],
        ),
    ]
