# Generated by Django 3.2.8 on 2021-11-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_soil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soil',
            name='name',
        ),
    ]
