# Generated by Django 3.2.8 on 2021-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0006_remove_soil_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='soil_order',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
