# Generated by Django 3.2.8 on 2021-11-01 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0008_auto_20211101_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='soil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gardens.soil'),
        ),
    ]
