# Generated by Django 3.2.8 on 2021-11-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0010_vegetables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vegetables',
            new_name='Vegetable',
        ),
    ]
