# Generated by Django 3.2.8 on 2021-11-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0011_rename_vegetables_vegetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='exposure',
            field=models.CharField(choices=[('FS', 'FS'), ('PS', 'PS'), ('BO', 'BO')], max_length=4),
        ),
    ]
