# Generated by Django 3.2.8 on 2021-11-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0012_alter_vegetable_exposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
