# Generated by Django 3.2.8 on 2021-11-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0013_vegetable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='adversaries',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='companions',
            field=models.JSONField(null=True),
        ),
    ]
