# Generated by Django 3.2.8 on 2021-11-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0014_auto_20211103_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='adversaries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='companions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
