# Generated by Django 3.2.8 on 2021-11-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0015_auto_20211103_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='vegetables',
            field=models.ManyToManyField(to='gardens.Vegetable'),
        ),
    ]
