# Generated by Django 3.2.8 on 2021-11-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0016_garden_vegetables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='vegetables',
            field=models.ManyToManyField(related_name='vegetables', to='gardens.Vegetable'),
        ),
    ]
