# Generated by Django 3.2.9 on 2021-11-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0017_alter_garden_vegetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='layout',
            field=models.ImageField(null=True, upload_to='layouts/'),
        ),
    ]
