# Generated by Django 3.2.9 on 2021-11-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0020_alter_garden_vegetables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='vegetables',
            field=models.ManyToManyField(related_name='vegetables', to='gardens.Vegetable'),
        ),
    ]
