# Generated by Django 3.2.9 on 2021-11-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0024_auto_20211105_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
