# Generated by Django 3.2.9 on 2021-11-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0027_alter_vegetable_exposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
