# Generated by Django 3.2.9 on 2021-11-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0028_vegetable_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='location',
        ),
        migrations.AddField(
            model_name='garden',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
